"""bigint

Revision ID: 4f79b4f44c12
Revises: 7f778a2c60ed
Create Date: 2020-06-03 18:45:14.098543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f79b4f44c12'
down_revision = '7f778a2c60ed'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('machineprocess', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger())
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('machineprocess', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER())
    # ### end Alembic commands ###
